Description: >
  Jonathan Llovet / IAM Permissions and User for DevOps Service Accounts

Parameters:
  Owner:
    Description: Email address of resource owner
    Type: String
    Default: replaceme@example.com
    # AllowedPattern: '/[^\s@]+@[^\s@]+\.[^\s@]+/'

  DevOpsServicePassword:
    Description: Password for DevOpsService user account
    Type: String

Resources:
  AllowFullAccessCICDEnvironmentPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: Grants access to resources required for Dev Ops Engineers working on CICD pipelines.
      ManagedPolicyName: Dev-Ops-S3-EC2-CloudWatch
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:*
              - cloudwatch:*
              - ec2:*
            Resource:
              - "*"

  DevOpsGroup:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: DevOps
      ManagedPolicyArns: 
        - !Ref AllowFullAccessCICDEnvironmentPolicy

  DevOpsGroupUserAdditions:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref DevOpsGroup
      Users:
        - !Ref DevOpsService

  DevOpsService:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - String
      LoginProfile:
        Password: !Ref DevOpsServicePassword
      ManagedPolicyArns:
        - !Ref AllowFullAccessCICDEnvironmentPolicy
      Tags:
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: DevOpsService
        - Key: Description
          Value: Service account to work on DevOps pipelines
      UserName:
        !Join
        - ""
        - - !Ref AWS::Region
          - "DevOpsService"
