Description: >
  Jonathan Llovet / Nginx Server in default VPC
  Definition of server

Parameters:
  Owner:
    Description: Email address of resource owner
    Type: String
    Default: replaceme@example.com
    # AllowedPattern: '/[^\s@]+@[^\s@]+\.[^\s@]+/'

  Environment:
    Description: Name of the environment - will be prefixed to resources
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Test
      - QA
      - Prod

  NginxServerKeyName:
    Description: Name of SSH Key used for web servers
    Type: String

  NginxServerInstanceType:
    Description: Nginx server instance type
    Type: String
    Default: t2.micro

Resources:
  NginxServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Nginx-Server-Security-Group
      GroupDescription: Allow HTTP Traffic to Nginx Server
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

  NginxServer:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Select [0, !GetAZs '']
      ImageId: ami-085925f297f89fce1
      UserData:
        # References:
        # https://www.udemy.com/course/nginx-fundamentals/learn/lecture/10607814#overview
        # https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units
        # https://stackoverflow.com/questions/82256/how-do-i-use-sudo-to-redirect-output-to-a-location-i-dont-have-permission-to-wr
        # https://stackoverflow.com/questions/10969953/how-to-output-a-multiline-string-in-bash
        Fn::Base64: !Sub |
          # !/bin/bash
          # Option 1: Install with Package Manager
          # sudo apt-get update
          # sudo apt-get install -y nginx
          # Option 2: Build From Source - Allows custom modules
          sudo apt-get update
          sudo wget http://nginx.org/download/nginx-1.19.0.tar.gz
          sudo tar -zxvf nginx-1.19.0.tar.gz
          cd nginx-1.19.0
          sudo apt-get install -y build-essential
          sudo apt-get install -y libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev
          sudo ./configure --sbin-path=/usr/bin/nginx --conf-path=/etc/nginx/nginx.conf \
          --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log \
          --with-pcre --pid-path=/var/run/nginx.pid --with-http_ssl_module
          sudo make
          sudo make install
          # Write service definition to file
          sudo touch /lib/systemd/system/nginx.service
          echo "[Unit]
          Description=The NGINX HTTP and reverse proxy server
          After=syslog.target network-online.target remote-fs.target nss-lookup.target
          Wants=network-online.target

          [Service]
          Type=forking
          PIDFile=/var/run/nginx.pid
          ExecStartPre=/usr/bin/nginx -t
          ExecStart=/usr/bin/nginx
          ExecReload=/usr/bin/nginx -s reload
          ExecStop=/bin/kill -s QUIT $MAINPID
          PrivateTmp=true
          
          [Install]
          WantedBy=multi-user.target" | sudo tee /lib/systemd/system/nginx.service > /dev/null
          # Start nginx service through systemd
          sudo systemctl start nginx
          # Set nginx to start up on system reboot
          sudo systemctl enable nginx

      InstanceType: !Ref NginxServerInstanceType
      KeyName: !Ref NginxServerKeyName
      SecurityGroupIds:
        - !Ref NginxServerSecurityGroup
      Tags:
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Sub "${Environment}-Nginx-Server"
